### ISSUE TITLE
Git tags, GitHub releases, PyPI releases

### ISSUE THREAD

**Issue by slobentanzer** [Teichlab/sctk#12]
Who will take care of tagging and releasing versions here and on PyPI?

The different release strategies are independent and do not all have to be implemented.

Explanation:

# Git tags:
In your terminal, in the repo directory, run:
```
bumpversion [patch|minor|major]
git push --tags
```

# GitHub releases
Selecting the corresponding tag, create a release including a description of the most pertinent changes.

# PyPI releases
After registering on PyPI.org and setting up permissions in your terminal, for each new release (as determined by the version in the `pyproject.toml`), run:
```
poetry build
poetry publish
```

**Comment by ktpolanski** [comment]
The current instructions allow a putative user to get the code working. This is not a high priority thing.

Once you're done with the various PRs (it's just the docs left at this point, after the guides, right?) I can put it up from my personal account.

**Comment by slobentanzer** [comment]
Agree, with one caveat: issues in setting up a package (basically having to go beyond `pip install sctk`) may detract from your number of putative users. At least that seems to be the general experience. Install from GitHub tends to come with some compatibility issues. It would also be useful for workflows (I think Batu wanted to wait for the PyPI version for the Nextflow pipeline).

**Comment by ktpolanski** [comment]
In that case all the more reason to get the docs and stuff sorted :P

**Comment by slobentanzer** [comment]
I think PyPI can be done right away, as packaging is independent of the documentation.

**Comment by ktpolanski** [comment]
https://pypi.org/project/sctk/

There's now a nice readme and links to things. Think it was worth the wait.
