### ISSUE TITLE
sctk does not import with scanpy 1.9.5 or 1.9.4

### ISSUE THREAD

**Issue by SimonDMurray** [Teichlab/sctk#15]
When trying to import sctk with scanpy 1.9.4 or scanpy 1.9.5 the following error is produced:
```
ImportError: cannot import name 'Literal' from 'scanpy._compat'
```

sctk still imports fine with scanpy 1.9.3

**Comment by ktpolanski** [comment]
Replicated, resolved. Install from GitHub to get the version with the weird `Literal` thing gone.

**Comment by slobentanzer** [comment]
@ktpolanski it may make sense to have a new release on PyPI as well?

**Comment by ktpolanski** [comment]
Done.

**Comment by slobentanzer** [comment]
nice, thanks :)
