### ISSUE TITLE
Add Sphinx documentation workflow with GitHub Action

### ISSUE THREAD

**Issue by slobentanzer** [Teichlab/sctk#5]
Add a Sphinx action with autodocumentation to generate a web page served by github pages (similar to https://github.com/biocypher/biocypher).

**Comment by ktpolanski** [comment]
any luck with this?

**Comment by ktpolanski** [comment]
I tend to favour a notebook-heavy style, with auxiliary docstring renders. As such, having the notebook and the docstrings for the four pertinent functions would be what I'd go for personally.

**Comment by slobentanzer** [comment]
The question is whether we need a web page for that. Web pages often are used to go beyond API documentation, for introduction, tutorials, other links, etc. Examples are https://scanpy.readthedocs.io/en/stable/ and https://biocypher.org.

If the audience consists more of specialists that just want the tool and a brief API description, the README could be enough.

"Four pertinent functions" relates to only the QC part, though. What are the plans for the rest of the package? At some point, the README may become unwieldy.

**Comment by ktpolanski** [comment]
All the more reason to have a simple documentation web page with the tutorial and the API for the four QC functions (plus also add the GMM one in as one of the other ones can mess with it via `**kwargs`). If there is growth, there is a natural place for the growth to occur.

**Comment by slobentanzer** [comment]
Sure, just wanted to make sure this is desired. Are you in favour of any particular theme? You can choose from [here](https://sphinx-themes.org).
